// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grvvrkhlgpadzbbhwcdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdydnZya2hsZ3BhZHpiYmh3Y2R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5NTIxNDQsImV4cCI6MjA1MzUyODE0NH0.j8tuIpNgwJjYW2VXmAOilQWwOVQycN0NZ2Fm63KkN-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);